version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
  build:
    commands:
      - . ./assume-role.sh ${ENV_PIPELINE_EXECUTION_ROLE} deploy
      - sam deploy --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --resolve-s3 --stack-name ${ENV_STACK_NAME} --parameter-overrides MyDeployEnvironment=‰{ENV_ENV}
      - . cd WebApllication/
      - . ./modify_config_and_cp_to_s3.sh
      #- sam deploy --stack-name ${ENV_STACK_NAME}
      #              --template ${ENV_TEMPLATE}
      #              --capabilities CAPABILITY_IAM
      #              --region ${ENV_REGION}
      #              --s3-bucket ${ENV_BUCKET}
      #              --no-fail-on-empty-changeset
      #              --role-arn ${ENV_CLOUDFORMATION_EXECUTION_ROLE}
